In [1]:
import numpy as np


In [3]:
list = [1,2,3]
list

[1, 2, 3]

In [8]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [16]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(5,43)


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42])

In [13]:
np.arange(5,40,4,dtype = "float")

array([ 5.,  9., 13., 17., 21., 25., 29., 33., 37.])

In [14]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [15]:
np.zeros(20,dtype= "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
np.ones(3,dtype="int")

array([1, 1, 1])

In [24]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
np.linspace(2,41,6)

array([ 2. ,  9.8, 17.6, 25.4, 33.2, 41. ])

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.eye(5,dtype="int")


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [31]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.random.randn(2,20)

array([[-1.98776188,  1.50415622, -1.12335306, -0.28465727,  0.48359326,
        -2.66302389, -0.11796928,  0.28303339,  0.01597961, -0.84348221,
         0.91826899,  1.83583112,  1.09806123, -0.61962415, -0.75342608,
         0.99144413,  1.15922577, -1.6490563 , -1.05551087, -0.55669189],
       [ 1.98658363,  1.23542706,  0.79447047,  0.2699478 , -0.35667619,
        -0.22403993,  0.37160498, -0.53285559, -2.73929446,  0.22585363,
         0.73182883, -2.01890505,  0.02578497,  1.84432924,  1.47702336,
        -0.3803822 , -1.4293188 ,  1.74207435, -0.03953525, -1.5858151 ]])

In [35]:
np.random.rand(2,20)

array([[0.07484454, 0.08467426, 0.03640251, 0.73742031, 0.40302554,
        0.86483465, 0.47091077, 0.65489415, 0.4607884 , 0.59478897,
        0.84372818, 0.1615009 , 0.86820193, 0.53007192, 0.55128045,
        0.00536041, 0.74649819, 0.86568688, 0.3313211 , 0.75563014],
       [0.63152518, 0.41391377, 0.8722112 , 0.50431622, 0.90994652,
        0.30579127, 0.88245157, 0.63218729, 0.91510657, 0.87995606,
        0.00872571, 0.59631508, 0.94120147, 0.6968863 , 0.99920373,
        0.62593749, 0.36119748, 0.86038756, 0.95676575, 0.03751208]])

In [37]:
np.random.randint(2,20)

15

In [40]:
np.random.randint(20,94,100)

array([75, 80, 24, 68, 71, 25, 78, 38, 73, 73, 65, 28, 35, 70, 87, 45, 75,
       80, 32, 60, 33, 84, 25, 63, 37, 51, 70, 36, 76, 23, 51, 92, 50, 83,
       51, 45, 47, 37, 88, 87, 85, 54, 72, 75, 31, 71, 70, 59, 77, 29, 45,
       31, 53, 58, 63, 92, 28, 43, 89, 74, 33, 90, 84, 28, 90, 56, 43, 47,
       60, 76, 52, 91, 51, 21, 75, 32, 35, 32, 92, 40, 52, 22, 76, 69, 57,
       44, 70, 69, 56, 48, 50, 85, 20, 21, 72, 40, 87, 24, 75, 42])

In [41]:
sample_array=np.arange(50)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [43]:
rand_array = np.random.randint(0,100,20)
rand_array

array([36, 40, 12,  0, 11,  3, 46, 40, 37, 18, 85, 38, 65, 16, 73, 37, 64,
       56, 32, 15])

In [44]:
rand_array.reshape(5,4)

array([[36, 40, 12,  0],
       [11,  3, 46, 40],
       [37, 18, 85, 38],
       [65, 16, 73, 37],
       [64, 56, 32, 15]])

In [45]:
rand_array.reshape(2,10)

array([[36, 40, 12,  0, 11,  3, 46, 40, 37, 18],
       [85, 38, 65, 16, 73, 37, 64, 56, 32, 15]])

In [47]:
rand_array.argmax()

10

In [49]:
sample_array.shape

(50,)

In [50]:
sample_array.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [51]:
sample_array.dtype

dtype('int32')

In [53]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
sample_array.min()

0

In [57]:
sample_array.max()

49

In [58]:
a=np.random.rand(2,3)
a

array([[0.66481257, 0.01095759, 0.08717076],
       [0.90064963, 0.41045795, 0.22709409]])

In [59]:
a.T

array([[0.66481257, 0.90064963],
       [0.01095759, 0.41045795],
       [0.08717076, 0.22709409]])

In [60]:
sample_matrix= np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [61]:
sample_matrix[0][3]

23

In [62]:
sample_matrix[:,0]

array([50, 24, 56])

In [63]:
sample_matrix[0,1:3]

array([20,  1])

In [64]:
sample_matrix[2]

array([56, 76, 24,  7])

In [65]:
sample_matrix[:,2]

array([ 1, 21, 24])

In [67]:
sample_matrix[1:3,1:3]

array([[23, 21],
       [76, 24]])

In [68]:
sample_matrix[0:2,(2,3)]

array([[ 1, 23],
       [21, 33]])

In [70]:
sample_array=np.arange(1,11)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
bool =sample_array<6
bool

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [74]:
sample_array[bool]

array([1, 2, 3, 4, 5])

In [75]:
sample_array+ sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [76]:
np.exp(sample_array)
np.round()

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [79]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [80]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [81]:
np.max(sample_array)

10

In [82]:
np.min(sample_array)

1

In [83]:
np.argmax(sample_array)

9

In [84]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [87]:
array=np.random.randn(3,5)
array

array([[ 0.18787042,  0.67354916,  0.9569965 ,  0.75197621,  0.65141484],
       [-0.25498396,  2.24209842,  0.33357973,  0.71300507,  0.55283318],
       [ 0.25334535, -1.13845965,  0.35572213,  1.07375273, -0.01571275]])

In [88]:
np.round(array,decimals=3)

array([[ 0.188,  0.674,  0.957,  0.752,  0.651],
       [-0.255,  2.242,  0.334,  0.713,  0.553],
       [ 0.253, -1.138,  0.356,  1.074, -0.016]])

In [2]:
sports=np.array(["g","h","e","r","g","q"])
np.unique(sports)

array(['e', 'g', 'h', 'q', 'r'], dtype='<U1')